### ISSUE TITLE
Physical edition

### ISSUE THREAD

**Issue by rakulnas** [Ramsis-SNES/furryrpg#1]
Hello;
  A friend told me about your project, looks really interesting. I would like to ask is you have editor for a physical cart release. I may do for you. If you are interested, please, contact me in info@nosolovintage.com 

Greeting and nice work :)

.: Felipe :.

**Comment by Ramsis-SNES** [comment]
Hi!

Thank you for your interest in this project.

Currently, FURRY RPG! is in an early state of development, and thusly far from being "released" in any shape or form.

Thanks again!
