### ISSUE TITLE
Fixed issue when compiling for newer version of wla

### ISSUE THREAD

**Issue by thefloppydriver** [Ramsis-SNES/furryrpg#2]
In **lib_macros.asm**:
  Line 472 (broken): `ldx	#(8*\1-2)<<8 + 8*\2`
  Line 472 (fixed): `ldx #8*\2 + 2048*\1 - 512`

1) You had your xpos and ypos backwards, it should be arg 2 then arg 1
2) They give the same result if the variables are switched, but wla doesn't like the first one.

**Comment by Ramsis-SNES** [comment]
First of all, welcome to my repository. :-)

As for your suggestion, I fixed this some time ago like so:

`	ldx	#((8*\1-2)<<8) + 8*\2
`

Repo will be updated (along with more recent changes) soon-ish.

**Comment by thefloppydriver** [comment]
Alright!

**Comment by thefloppydriver** [comment]
Also I would like to let you know that your repository is basically the only working example of working snesgss code with the wla-dx compiler, and the only working exhirom configuration with the wla-dx compiler. I don't know if you'd be up for this kind of thing or not but if you could write some tutorials on using this software and how you did it that'd be a lifesaver for anyone developing using these software. Thanks :)
